#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFA_25038.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFB_26208.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFC_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFD_28399.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFE_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/ORFF_8017.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/sORF4_139953.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/sORF4_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL0_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL10_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL11_94145.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL12_92676.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL13_91099.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL14_90482.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL17_87242.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL18_84946.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL1_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL20_79669.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL21_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL23_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL25_35149.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL26_37044.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL265_37908.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL2_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL31_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL33_53510.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL34_53904.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL35_54802.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL35_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL38_66926.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL3_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL40_70872.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL4_106290.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL41_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL43_74676.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL44_76570.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL45_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL46_21648.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL47_129034.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL49_19509.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL495_19096.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL50_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL5_103682.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL51_16949.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL53_complement.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL54_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL56_7062.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL7_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL8_98265.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/UL_complement.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US10_124521.pat sequence.fasta
java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US10_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US2_complement.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US3_127518.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US4_131069.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US6_134922.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US7_136334.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US8_137616.pat sequence.fasta
#java -Xss1024m -jar target/string-matcher-1.0-SNAPSHOT-jar-with-dependencies.jar genes/US9_139122.pat sequence.fasta